In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
#Example of directed adjacency matrix 
adj=np.array([[0,1,0,0,1,0],[0,0,1,1,0,1],[1,0,0,0,1,0],[0,0,0,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0]])

In [4]:
adj

array([[0, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [6]:
adjT=adj.T

In [7]:
adjT

array([[0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0]])

In [8]:
#undirected adjacency matrix
adj_undir= np.maximum(adj, adj.T)

In [9]:
adj_undir

array([[0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 1],
       [0, 1, 0, 0, 1, 0]])

In [18]:
np.linalg.matrix_power(adj_undir, 3)[0][0]

4

In [20]:
def compute_paths(adjacency, source, target, length):
    """Compute the number of paths of a given length between a source and target node.
    
    Parameters
    ----------
    adjacency: numpy array
        The (weighted) adjacency matrix of a graph.
    source: int
        The source node. A number between 0 and n_nodes-1.
    target: int
        The target node. A number between 0 and n_nodes-1.
    length: int
        The path length to be considered.
    
    Returns
    -------
    int
        The number of paths.
    """
    n_paths=np.linalg.matrix_power(adjacency, length)[source][target]
    # Your code here.
    
    return n_paths

In [24]:
print (compute_paths(adj_undir,3,0,2))

2


In [29]:
int(np.sum(np.linalg.matrix_power(adj_undir,2)))

58

In [31]:
np.linalg.matrix_power(adj_undir,2)

array([[3, 1, 2, 2, 1, 2],
       [1, 4, 1, 0, 4, 0],
       [2, 1, 3, 2, 1, 2],
       [2, 0, 2, 2, 0, 2],
       [1, 4, 1, 0, 4, 0],
       [2, 0, 2, 2, 0, 2]])

In [32]:
degree= np.sum(adj_undir, axis= 0)

In [33]:
degree

array([3, 4, 3, 2, 4, 2])

In [34]:
L= np.linalg.matrix_power(adj_undir,3)[0][0]/2
k= degree[0]    
clustering_coefficient= L/(k*(k-1))

In [35]:
clustering_coefficient

0.3333333333333333

In [42]:
adjacency_undirected_power_3=np.linalg.matrix_power(adj_undir,3)
n_nodes=6

In [43]:
def compute_clustering_coefficient(adjacency, node):
    """Compute the clustering coefficient of a node.
    
    Parameters
    ----------
    adjacency: numpy array
        The (weighted) adjacency matrix of a graph.
    node: int
        The node whose clustering coefficient will be computed. A number between 0 and n_nodes-1.
    
    Returns
    -------
    float
        The clustering coefficient of the node. A number between 0 and 1.
    """
    
    L= adjacency_undirected_power_3[node][node]/2
    k= degree[node]
    
    clustering_coefficient= L/(k*(k-1))
    
    return clustering_coefficient

In [59]:
compute_clustering_coefficient(adj_undir, 5)

0.0

In [64]:
average_clustering_coefficient=0 
for i in range (0, n_nodes-1):
    average_clustering_coefficient+= compute_clustering_coefficient(adj_undir, i)
    
average_clustering_coefficient=average_clustering_coefficient/n_nodes

print('The average clustering coeffcient of our network is '+str(average_clustering_coefficient))

The average clustering coeffcient of our network is 0.1388888888888889


In [67]:
np.sum(np.diag(adjacency_undirected_power_3)/(2*degree*(degree-1)))/n_nodes

0.1388888888888889